# Generated by Django 5.0.6 on 2024-10-15 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AreaDeInteresse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("backend", models.BooleanField(default=False)),
                ("frontend", models.BooleanField(default=False)),
                ("banco_de_dados", models.BooleanField(default=False)),
                ("ui_ux_designer", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="EntreEmContato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100)),
                ("mensagem", models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Linguagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("python", models.BooleanField(default=False)),
                ("javascript", models.BooleanField(default=False)),
                ("java", models.BooleanField(default=False)),
                ("csharp", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Turno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matutino", models.BooleanField(default=False)),
                ("diurno", models.BooleanField(default=False)),
                ("noturno", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("sobrenome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("whatsapp", models.CharField(blank=True, max_length=25, null=True)),
                ("disponibilidade", models.DateTimeField(blank=True, null=True)),
                (
                    "area_de_interesse",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contacts.areadeinteresse",
                    ),
                ),
                (
                    "linguagem",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contacts.linguagem",
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contacts.turno",
                    ),
                ),
            ],
        ),
    ]
