# Generated by Django 5.0.6 on 2024-06-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('whatsapp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('area_interest', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('fullstack', 'Fullstack'), ('mobile', 'Mobile'), ('qa', 'QA'), ('ux/ui', 'UX/UI'), ('database', 'Database')], max_length=15)),
                ('language', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('c', 'C'), ('c++', 'C++'), ('c#', 'C#'), ('javascript', 'Javascript'), ('typescript', 'Typescript'), ('php', 'PHP'), ('ruby', 'Ruby'), ('go', 'Go'), ('scala', 'Scala'), ('swift', 'Swift'), ('kotlin', 'Kotlin')], max_length=15)),
                ('availability', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=10)),
            ],
        ),
    ]
